"""sprint04_honorarios_pagos

Revision ID: 0916d762e7cd
Revises: 91e6d398e2a5
Create Date: 2026-04-15 19:23:38.305502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0916d762e7cd'
down_revision: Union[str, None] = '91e6d398e2a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('honorarios',
    sa.Column('expediente_id', sa.String(), nullable=False),
    sa.Column('concepto', sa.String(length=500), nullable=False),
    sa.Column('monto_acordado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', sa.Enum('ARS', 'USD', name='moneda'), nullable=False),
    sa.Column('fecha_acuerdo', sa.String(length=10), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honorarios_expediente_id'), 'honorarios', ['expediente_id'], unique=False)
    op.create_index(op.f('ix_honorarios_tenant_id'), 'honorarios', ['tenant_id'], unique=False)
    op.create_table('pagos_honorarios',
    sa.Column('honorario_id', sa.String(), nullable=False),
    sa.Column('importe', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', sa.Enum('ARS', 'USD', name='moneda'), nullable=False),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('comprobante', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['honorario_id'], ['honorarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_honorarios_honorario_id'), 'pagos_honorarios', ['honorario_id'], unique=False)
    op.create_index(op.f('ix_pagos_honorarios_tenant_id'), 'pagos_honorarios', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_honorarios_tenant_id'), table_name='pagos_honorarios')
    op.drop_index(op.f('ix_pagos_honorarios_honorario_id'), table_name='pagos_honorarios')
    op.drop_table('pagos_honorarios')
    op.drop_index(op.f('ix_honorarios_tenant_id'), table_name='honorarios')
    op.drop_index(op.f('ix_honorarios_expediente_id'), table_name='honorarios')
    op.drop_table('honorarios')
    # ### end Alembic commands ###
