"""add_domicilio_to_clientes

Revision ID: 14496e67506f
Revises: c9f3f5499274
Create Date: 2026-04-21 18:07:34.902144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '14496e67506f'
down_revision: Union[str, None] = 'c9f3f5499274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('domicilio', sa.String(length=500), nullable=True))
    op.add_column('clientes', sa.Column('domicilio_lat', sa.Float(), nullable=True))
    op.add_column('clientes', sa.Column('domicilio_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'domicilio_lng')
    op.drop_column('clientes', 'domicilio_lat')
    op.drop_column('clientes', 'domicilio')
    # ### end Alembic commands ###
