"""add_hora_to_tareas

Revision ID: 17c09542f9a2
Revises: 14496e67506f
Create Date: 2026-04-21 18:15:33.668308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '17c09542f9a2'
down_revision: Union[str, None] = '14496e67506f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas', sa.Column('hora', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas', 'hora')
    # ### end Alembic commands ###
