"""add_numero_judicial_localidad_hora_dni_cuit_fecha_movimiento

Revision ID: 242ba4e976de
Revises: f5e21ed7929a
Create Date: 2026-04-21 17:00:40.716793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '242ba4e976de'
down_revision: Union[str, None] = 'f5e21ed7929a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('dni', sa.String(length=20), nullable=True))
    op.add_column('clientes', sa.Column('cuit', sa.String(length=20), nullable=True))
    op.execute("DROP INDEX IF EXISTS ix_clientes_fts")
    op.add_column('expedientes', sa.Column('numero_judicial', sa.String(length=200), nullable=True))
    op.add_column('expedientes', sa.Column('localidad', sa.String(length=200), nullable=True))
    op.execute("DROP INDEX IF EXISTS ix_expedientes_fts")
    op.create_index(op.f('ix_expedientes_numero_judicial'), 'expedientes', ['numero_judicial'], unique=False)
    op.add_column('movimientos', sa.Column('fecha_manual', sa.String(length=10), nullable=True))
    op.add_column('vencimientos', sa.Column('hora', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vencimientos', 'hora')
    op.drop_column('movimientos', 'fecha_manual')
    op.drop_index(op.f('ix_expedientes_numero_judicial'), table_name='expedientes')
    op.create_index('ix_expedientes_fts', 'expedientes', [sa.text("to_tsvector('spanish'::regconfig, (COALESCE(numero, ''::character varying)::text || ' '::text) || COALESCE(caratula, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.drop_column('expedientes', 'localidad')
    op.drop_column('expedientes', 'numero_judicial')
    op.create_index('ix_clientes_fts', 'clientes', [sa.text("to_tsvector('spanish'::regconfig, (COALESCE(nombre, ''::character varying)::text || ' '::text) || COALESCE(cuit_dni, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.drop_column('clientes', 'cuit')
    op.drop_column('clientes', 'dni')
    # ### end Alembic commands ###
