"""add_google_calendar_id_to_users

Revision ID: 255ad9d19349
Revises: 743b87a56c88
Create Date: 2026-04-15 21:38:13.527825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '255ad9d19349'
down_revision: Union[str, None] = '743b87a56c88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_calendar_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_calendar_id')
    # ### end Alembic commands ###
