"""add_trial_ends_at_to_studios

Revision ID: 2ceee8661236
Revises: 6d3919498d64
Create Date: 2026-04-21 11:24:32.445251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2ceee8661236'
down_revision: Union[str, None] = '6d3919498d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studios', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studios', 'trial_ends_at')
    # ### end Alembic commands ###
