"""add feriados_cache and dias_inhabiles tables

Revision ID: 2d4a964522d2
Revises: a7658760af6a
Create Date: 2026-04-21 20:24:46.481150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2d4a964522d2'
down_revision: Union[str, None] = 'a7658760af6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dias_inhabiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dias_inhabiles_fecha'), 'dias_inhabiles', ['fecha'], unique=False)
    op.create_index(op.f('ix_dias_inhabiles_tenant_id'), 'dias_inhabiles', ['tenant_id'], unique=False)
    op.create_table('feriados_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feriados_cache_anio'), 'feriados_cache', ['anio'], unique=False)
    op.create_index(op.f('ix_feriados_cache_fecha'), 'feriados_cache', ['fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feriados_cache_fecha'), table_name='feriados_cache')
    op.drop_index(op.f('ix_feriados_cache_anio'), table_name='feriados_cache')
    op.drop_table('feriados_cache')
    op.drop_index(op.f('ix_dias_inhabiles_tenant_id'), table_name='dias_inhabiles')
    op.drop_index(op.f('ix_dias_inhabiles_fecha'), table_name='dias_inhabiles')
    op.drop_table('dias_inhabiles')
    # ### end Alembic commands ###
