"""create tareas table

Revision ID: 3bacddf28e63
Revises: 7bff06be2a5e
Create Date: 2026-04-16 02:26:59.419278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3bacddf28e63'
down_revision: Union[str, None] = '7bff06be2a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('expediente_id', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('responsable_id', sa.String(), nullable=True),
    sa.Column('fecha_limite', sa.String(length=10), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'en_curso', 'hecha', name='tareaestado'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tareas_expediente_id'), 'tareas', ['expediente_id'], unique=False)
    op.create_index(op.f('ix_tareas_responsable_id'), 'tareas', ['responsable_id'], unique=False)
    op.create_index(op.f('ix_tareas_tenant_id'), 'tareas', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tareas_tenant_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_responsable_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_expediente_id'), table_name='tareas')
    op.drop_table('tareas')
    # ### end Alembic commands ###
