"""ingresos_tabla

Revision ID: 544abacdc514
Revises: f27b7451a547
Create Date: 2026-04-15 22:47:14.344593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '544abacdc514'
down_revision: Union[str, None] = 'f27b7451a547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingresos',
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('categoria', postgresql.ENUM('honorarios_cobrados', 'reintegros', 'consultas', 'otros', name='ingresocategoria'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', postgresql.ENUM('ARS', 'USD', name='moneda', create_type=False), nullable=False),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.String(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingresos_expediente_id'), 'ingresos', ['expediente_id'], unique=False)
    op.create_index(op.f('ix_ingresos_tenant_id'), 'ingresos', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingresos_tenant_id'), table_name='ingresos')
    op.drop_index(op.f('ix_ingresos_expediente_id'), table_name='ingresos')
    op.drop_table('ingresos')
    # ### end Alembic commands ###
