"""add reset_password_fields_to_users

Revision ID: 5ab6ab3c6892
Revises: 25a4bc4a240a
Create Date: 2026-04-20 15:24:17.624588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5ab6ab3c6892'
down_revision: Union[str, None] = '25a4bc4a240a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clientes_fts', table_name='clientes', postgresql_using='gin')
    op.drop_index('ix_expedientes_fts', table_name='expedientes', postgresql_using='gin')
    op.add_column('users', sa.Column('reset_password_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_password_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_reset_password_token'), 'users', ['reset_password_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_password_token'), table_name='users')
    op.drop_column('users', 'reset_password_expires_at')
    op.drop_column('users', 'reset_password_token')
    op.create_index('ix_expedientes_fts', 'expedientes', [sa.text("to_tsvector('spanish'::regconfig, (COALESCE(numero, ''::character varying)::text || ' '::text) || COALESCE(caratula, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.create_index('ix_clientes_fts', 'clientes', [sa.text("to_tsvector('spanish'::regconfig, (COALESCE(nombre, ''::character varying)::text || ' '::text) || COALESCE(cuit_dni, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
