"""add_flag_paralizado_to_expedientes

Revision ID: 5fa0ba36dbc4
Revises: da8f301c6977
Create Date: 2026-04-23 13:22:53.893438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5fa0ba36dbc4'
down_revision: Union[str, None] = 'da8f301c6977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expedientes', sa.Column('flag_paralizado', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expedientes', 'flag_paralizado')
    # ### end Alembic commands ###
