"""studio_logo_url_text

Revision ID: 6d3919498d64
Revises: d67e681c5b5e
Create Date: 2026-04-20 20:56:36.040004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6d3919498d64'
down_revision: Union[str, None] = 'd67e681c5b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('studios', 'logo_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('studios', 'logo_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
