"""add_gastos_table

Revision ID: 743b87a56c88
Revises: a991068fd9dd
Create Date: 2026-04-15 21:33:22.819922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '743b87a56c88'
down_revision: Union[str, None] = 'a991068fd9dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gastos',
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('categoria', sa.Enum('alquiler', 'sueldos', 'servicios', 'costos_judiciales', 'honorarios_terceros', 'otros', name='gastocategoria'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', postgresql.ENUM('ARS', 'USD', name='moneda', create_type=False), nullable=False),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('expediente_id', sa.String(), nullable=True),
    sa.Column('recurrente', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_expediente_id'), 'gastos', ['expediente_id'], unique=False)
    op.create_index(op.f('ix_gastos_tenant_id'), 'gastos', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gastos_tenant_id'), table_name='gastos')
    op.drop_index(op.f('ix_gastos_expediente_id'), table_name='gastos')
    op.drop_table('gastos')
    # ### end Alembic commands ###
