"""add expediente_resumenes table

Revision ID: 7be62acadaaf
Revises: 3bacddf28e63
Create Date: 2026-04-16 13:20:09.731791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7be62acadaaf'
down_revision: Union[str, None] = '3bacddf28e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expediente_resumenes',
    sa.Column('expediente_id', sa.String(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('generado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_contexto', sa.Integer(), nullable=False),
    sa.Column('version_resumen', sa.Integer(), nullable=False),
    sa.Column('regeneraciones_hoy', sa.Integer(), nullable=False),
    sa.Column('ultima_regeneracion_fecha', sa.String(length=10), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'expediente_id', name='uq_resumen_tenant_expediente')
    )
    op.create_index(op.f('ix_expediente_resumenes_expediente_id'), 'expediente_resumenes', ['expediente_id'], unique=False)
    op.create_index(op.f('ix_expediente_resumenes_tenant_id'), 'expediente_resumenes', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expediente_resumenes_tenant_id'), table_name='expediente_resumenes')
    op.drop_index(op.f('ix_expediente_resumenes_expediente_id'), table_name='expediente_resumenes')
    op.drop_table('expediente_resumenes')
    # ### end Alembic commands ###
