"""add tareas table

Revision ID: 7bff06be2a5e
Revises: ab7c536d2464
Create Date: 2026-04-16 02:26:04.600289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7bff06be2a5e'
down_revision: Union[str, None] = 'ab7c536d2464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
