"""add_expediente_clientes_table

Revision ID: 9244fd2d6242
Revises: 242ba4e976de
Create Date: 2026-04-21 17:26:56.869946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9244fd2d6242'
down_revision: Union[str, None] = '242ba4e976de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expediente_clientes',
    sa.Column('expediente_id', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expediente_clientes_cliente_id'), 'expediente_clientes', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_expediente_clientes_expediente_id'), 'expediente_clientes', ['expediente_id'], unique=False)
    op.create_index(op.f('ix_expediente_clientes_tenant_id'), 'expediente_clientes', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expediente_clientes_tenant_id'), table_name='expediente_clientes')
    op.drop_index(op.f('ix_expediente_clientes_expediente_id'), table_name='expediente_clientes')
    op.drop_index(op.f('ix_expediente_clientes_cliente_id'), table_name='expediente_clientes')
    op.drop_table('expediente_clientes')
    # ### end Alembic commands ###
