"""subscription_and_superadmin

Revision ID: 9da2c898a171
Revises: 2d4a964522d2
Create Date: 2026-04-22 14:05:09.526443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9da2c898a171'
down_revision: Union[str, None] = '2d4a964522d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_snapshots_snapshot_at'), 'metrics_snapshots', ['snapshot_at'], unique=False)
    op.create_table('plan_prices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan', sa.String(length=30), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.String(length=30), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mp_payment_id', sa.String(length=100), nullable=True),
    sa.Column('mp_preapproval_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_events_tenant_id'), 'subscription_events', ['tenant_id'], unique=False)
    op.add_column('studios', sa.Column('plan', sa.String(length=30), nullable=False, server_default='trial'))
    op.add_column('studios', sa.Column('billing_cycle', sa.String(length=20), nullable=True))
    op.add_column('studios', sa.Column('subscription_id', sa.String(length=100), nullable=True))
    op.add_column('studios', sa.Column('subscription_status', sa.String(length=30), nullable=True))
    op.add_column('studios', sa.Column('next_billing_date', sa.String(length=10), nullable=True))
    op.add_column('studios', sa.Column('plan_price_id', sa.String(length=100), nullable=True))
    op.add_column('studios', sa.Column('subscription_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superadmin')
    op.drop_column('studios', 'subscription_updated_at')
    op.drop_column('studios', 'plan_price_id')
    op.drop_column('studios', 'next_billing_date')
    op.drop_column('studios', 'subscription_status')
    op.drop_column('studios', 'subscription_id')
    op.drop_column('studios', 'billing_cycle')
    op.drop_column('studios', 'plan')
    op.drop_index(op.f('ix_subscription_events_tenant_id'), table_name='subscription_events')
    op.drop_table('subscription_events')
    op.drop_table('plan_prices')
    op.drop_index(op.f('ix_metrics_snapshots_snapshot_at'), table_name='metrics_snapshots')
    op.drop_table('metrics_snapshots')
    # ### end Alembic commands ###
