"""add cliente_id to ingresos and gastos

Revision ID: a7658760af6a
Revises: e9b46f338ee1
Create Date: 2026-04-21 20:16:45.165603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a7658760af6a'
down_revision: Union[str, None] = 'e9b46f338ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos', sa.Column('cliente_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_gastos_cliente_id'), 'gastos', ['cliente_id'], unique=False)
    op.create_foreign_key(None, 'gastos', 'clientes', ['cliente_id'], ['id'])
    op.add_column('ingresos', sa.Column('cliente_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_ingresos_cliente_id'), 'ingresos', ['cliente_id'], unique=False)
    op.create_foreign_key(None, 'ingresos', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingresos', type_='foreignkey')
    op.drop_index(op.f('ix_ingresos_cliente_id'), table_name='ingresos')
    op.drop_column('ingresos', 'cliente_id')
    op.drop_constraint(None, 'gastos', type_='foreignkey')
    op.drop_index(op.f('ix_gastos_cliente_id'), table_name='gastos')
    op.drop_column('gastos', 'cliente_id')
    # ### end Alembic commands ###
