"""sprint05_documentos

Revision ID: a991068fd9dd
Revises: 0916d762e7cd
Create Date: 2026-04-15 20:29:17.775910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a991068fd9dd'
down_revision: Union[str, None] = '0916d762e7cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('expediente_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_expediente_id'), 'documentos', ['expediente_id'], unique=False)
    op.create_index(op.f('ix_documentos_tenant_id'), 'documentos', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentos_tenant_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_expediente_id'), table_name='documentos')
    op.drop_table('documentos')
    # ### end Alembic commands ###
