"""tareas

Revision ID: ab7c536d2464
Revises: cc1fd28b83fc
Create Date: 2026-04-16 01:07:33.998603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ab7c536d2464'
down_revision: Union[str, None] = 'cc1fd28b83fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
