"""add_tipo_to_tareas

Revision ID: b05941eaead4
Revises: 17c09542f9a2
Create Date: 2026-04-21 18:20:20.153217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b05941eaead4'
down_revision: Union[str, None] = '17c09542f9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE TYPE tareatipo AS ENUM ('judicial', 'extrajudicial', 'administrativa')")
    op.add_column('tareas', sa.Column('tipo', sa.Enum('judicial', 'extrajudicial', 'administrativa', name='tareatipo', create_type=False), nullable=False, server_default='judicial'))
    op.alter_column('tareas', 'tipo', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas', 'tipo')
    # ### end Alembic commands ###
