"""add_tarea_id_vencimiento_id_to_documentos

Revision ID: c9f3f5499274
Revises: 9244fd2d6242
Create Date: 2026-04-21 17:56:30.399296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c9f3f5499274'
down_revision: Union[str, None] = '9244fd2d6242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('tarea_id', sa.String(), nullable=True))
    op.add_column('documentos', sa.Column('vencimiento_id', sa.String(), nullable=True))
    op.alter_column('documentos', 'expediente_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_documentos_tarea_id'), 'documentos', ['tarea_id'], unique=False)
    op.create_index(op.f('ix_documentos_vencimiento_id'), 'documentos', ['vencimiento_id'], unique=False)
    op.create_foreign_key(None, 'documentos', 'tareas', ['tarea_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'documentos', 'vencimientos', ['vencimiento_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documentos', type_='foreignkey')
    op.drop_constraint(None, 'documentos', type_='foreignkey')
    op.drop_index(op.f('ix_documentos_vencimiento_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_tarea_id'), table_name='documentos')
    op.alter_column('documentos', 'expediente_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documentos', 'vencimiento_id')
    op.drop_column('documentos', 'tarea_id')
    # ### end Alembic commands ###
