"""pagos_honorarios_tipo

Revision ID: cc1fd28b83fc
Revises: 544abacdc514
Create Date: 2026-04-15 23:11:54.048619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cc1fd28b83fc'
down_revision: Union[str, None] = '544abacdc514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos_honorarios', sa.Column('tipo', sa.String(length=20), nullable=False, server_default='capital'))
    op.alter_column('pagos_honorarios', 'tipo', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagos_honorarios', 'tipo')
    # ### end Alembic commands ###
