"""make_tarea_expediente_id_nullable

Revision ID: d67e681c5b5e
Revises: 5ab6ab3c6892
Create Date: 2026-04-20 18:32:24.795471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd67e681c5b5e'
down_revision: Union[str, None] = '5ab6ab3c6892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tareas', 'expediente_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tareas', 'expediente_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
