"""add_flag_paralizado_to_tareas

Revision ID: da8f301c6977
Revises: dd8a608d6ac3
Create Date: 2026-04-23 13:06:08.270013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'da8f301c6977'
down_revision: Union[str, None] = 'dd8a608d6ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas', sa.Column('flag_paralizado', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas', 'flag_paralizado')
    # ### end Alembic commands ###
