"""add_notas_table

Revision ID: dd8a608d6ac3
Revises: 9da2c898a171
Create Date: 2026-04-22 16:34:31.817776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd8a608d6ac3'
down_revision: Union[str, None] = '9da2c898a171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas',
    sa.Column('tarea_id', sa.String(), nullable=True),
    sa.Column('vencimiento_id', sa.String(), nullable=True),
    sa.Column('autor_id', sa.String(), nullable=True),
    sa.Column('autor_nombre', sa.String(length=200), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vencimiento_id'], ['vencimientos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_tarea_id'), 'notas', ['tarea_id'], unique=False)
    op.create_index(op.f('ix_notas_tenant_id'), 'notas', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notas_vencimiento_id'), 'notas', ['vencimiento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notas_vencimiento_id'), table_name='notas')
    op.drop_index(op.f('ix_notas_tenant_id'), table_name='notas')
    op.drop_index(op.f('ix_notas_tarea_id'), table_name='notas')
    op.drop_table('notas')
    # ### end Alembic commands ###
