"""add cliente_id to tareas

Revision ID: e9b46f338ee1
Revises: 6b8b40123572
Create Date: 2026-04-21 19:04:09.918570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e9b46f338ee1'
down_revision: Union[str, None] = '6b8b40123572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas', sa.Column('cliente_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_tareas_cliente_id'), 'tareas', ['cliente_id'], unique=False)
    op.create_foreign_key(None, 'tareas', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tareas', type_='foreignkey')
    op.drop_index(op.f('ix_tareas_cliente_id'), table_name='tareas')
    op.drop_column('tareas', 'cliente_id')
    # ### end Alembic commands ###
