"""contable_plantillas_estado_mes_anio

Revision ID: f27b7451a547
Revises: 255ad9d19349
Create Date: 2026-04-15 22:03:01.852106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'f27b7451a547'
down_revision: Union[str, None] = '255ad9d19349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gasto_plantillas',
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('categoria', postgresql.ENUM('alquiler', 'sueldos', 'servicios', 'costos_judiciales', 'honorarios_terceros', 'otros', name='gastocategoria', create_type=False), nullable=False),
    sa.Column('monto_esperado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', postgresql.ENUM('ARS', 'USD', name='moneda', create_type=False), nullable=False),
    sa.Column('dia_del_mes', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gasto_plantillas_tenant_id'), 'gasto_plantillas', ['tenant_id'], unique=False)
    gastoestado = postgresql.ENUM('pendiente', 'confirmado', name='gastoestado')
    gastoestado.create(op.get_bind())
    op.add_column('gastos', sa.Column('mes', sa.Integer(), nullable=True))
    op.add_column('gastos', sa.Column('anio', sa.Integer(), nullable=True))
    op.add_column('gastos', sa.Column('estado', postgresql.ENUM('pendiente', 'confirmado', name='gastoestado', create_type=False), nullable=True))
    # Backfill existing rows
    op.execute("UPDATE gastos SET mes = EXTRACT(MONTH FROM fecha::date), anio = EXTRACT(YEAR FROM fecha::date), estado = 'confirmado' WHERE mes IS NULL")
    op.alter_column('gastos', 'mes', nullable=False)
    op.alter_column('gastos', 'anio', nullable=False)
    op.alter_column('gastos', 'estado', nullable=False)
    op.add_column('gastos', sa.Column('plantilla_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_gastos_plantilla_id'), 'gastos', ['plantilla_id'], unique=False)
    op.create_foreign_key(None, 'gastos', 'gasto_plantillas', ['plantilla_id'], ['id'])
    op.drop_column('gastos', 'recurrente')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos', sa.Column('recurrente', sa.BOOLEAN(), autoincrement=False, nullable=True))
    postgresql.ENUM('pendiente', 'confirmado', name='gastoestado').drop(op.get_bind())
    op.drop_constraint(None, 'gastos', type_='foreignkey')
    op.drop_index(op.f('ix_gastos_plantilla_id'), table_name='gastos')
    op.drop_column('gastos', 'plantilla_id')
    op.drop_column('gastos', 'estado')
    op.drop_column('gastos', 'anio')
    op.drop_column('gastos', 'mes')
    op.drop_index(op.f('ix_gasto_plantillas_tenant_id'), table_name='gasto_plantillas')
    op.drop_table('gasto_plantillas')
    # ### end Alembic commands ###
