"""add_label_orden_to_documentos

Revision ID: f5e21ed7929a
Revises: 2ceee8661236
Create Date: 2026-04-21 12:46:43.750944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f5e21ed7929a'
down_revision: Union[str, None] = '2ceee8661236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('label', sa.String(length=200), nullable=True))
    op.add_column('documentos', sa.Column('orden', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos', 'orden')
    op.drop_column('documentos', 'label')
    # ### end Alembic commands ###
